/* MTI_DPI */

/*
 * Copyright 2002-2015 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
create_sv_dynarray();

DPI_LINK_DECL DPI_DLLESPEC
void
fetch_sv_dynarray_data_from_C(
    void* cdata,
    const svOpenArrayHandle o);

DPI_LINK_DECL void
alloc_sv_dynarray(
    int size,
    void* cdata);

#endif 
