/* MTI_DPI */

/*
 * Copyright 2002-2015 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32'
 */
#ifndef INCLUDED_DPI_TYPES
#define INCLUDED_DPI_TYPES

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
c_CarWaiting();

DPI_LINK_DECL void
sv_RedLight();

DPI_LINK_DECL int
sv_WaitForRed();

DPI_LINK_DECL void
sv_YellowLight();

#endif 
